name: Run OpenAI Summary (Manual or PR)

on:
  workflow_dispatch:  # Enables manual trigger
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get PR Diff
      run: |
        echo "Fetching PR diff..."
        gh pr diff ${{ github.event.pull_request.number }} > pr.diff
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Call OpenAI to summarize
      run: |
        DIFF=$(cat pr.diff | head -c 4000)
        RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
          -s \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
          -d "{
            \"model\": \"gpt-4o\",
            \"messages\": [
              {\"role\": \"system\", \"content\": \"You are a senior code reviewer.\"},
              {\"role\": \"user\", \"content\": \"Summarize this diff:\n$DIFF\"}
            ]
          }")

        echo "$RESPONSE" | jq -r '.choices[0].message.content'
